package com.property_insurance.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PoliceOfficer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String badge;

	public PoliceOfficer() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getBadge() {
		return this.badge;
	}

	public void setBadge(java.lang.String badge) {
		this.badge = badge;
	}

	public PoliceOfficer(java.lang.String name, java.lang.String badge) {
		this.name = name;
		this.badge = badge;
	}

}